version: "3.9"
services:
  infracloud:
    image: infracloudio/csvserver
    ports:
      - 9393:9300
    environment:
      - CSVSERVER_BORDER=Orange
    volumes:
     - type: bind
       source: C:/shell/inputFile
       target: /csvserver/inputdata

  prometheus_monitor:
     image: prom/prometheus:v2.22.0
     volumes:
       - type: bind
         source: C:/shell/prometheus.yaml
         target: /etc/prometheus/prometheus.yml
     ports:
       - 9090:9090